import { ChakraProvider } from "@chakra-ui/react";

import { Header } from "@/presentation/components";

import "@/configs/styles/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ChakraProvider>
      <Header />
      {children}
    </ChakraProvider>
  );
}
